spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-proud-block-ahctzakb.c-3.us-east-1.aws.neon.tech:5432/neondb}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_fsNFdUa31jCS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
